openapi: 3.0.1
info:
  title: STD21033 API
  description: 'Global description of my API'
  version: 1.0.0
servers:
 - url: https://STD21033.com
tags: 
 - name: Students
   
 - name: Courses
paths:
 /students:
    get:
      tags:
        - Students
      operationId: getStudents
      summary: Get all students
      description: Get all students with details
      responses:
        200: 
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Student'
        400:
          description: Bad request
    post: 
      tags:
        - Students
      operationId: createStudent
      summary : Create new student
      description: Create new student
      requestBody:
        description: Student to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudent'
        required: true
      responses:
        200:
          description: List of students
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        400:
          description: Bad request
    patch: 
      tags:
        - Students
      operationId: updateStudent
      summary : Update information of an student
      description: Update information of an student
      requestBody:
        description: Student updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudent'
            examples:
              changeName:
                summary: Change name
                description: How to change name and what it does
                value:
                  id: 1
                  name: "New name"
              changeAddress:
                summary: Change address
                value:
                  id: 1
                  name: "Ivandry"
              changeNameAndAddress:
                summary: Change name and address but not all
                value:
                  id: 1
                  name: "New name"
                  address: "Ivandry"
              changePhoneNumbers:
                summary: Change phone number
                value:
                  id: 1
                  number:
                  - country-code: "+261"
                    number: "0347570893"
        required: true
      responses:
        200:
          description: List of students
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        400:
          description: Bad request
    put: 
      tags:
        - Students
      operationId: updateStudent
      summary : Update information of an student
      description: Update information of an student
      requestBody:
        description: Student updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudent'
        required: true
      responses:
        200:
          description: List of students
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        400:
          description: Bad request
 /Courses:
    get:
      tags:
        - Courses
      operationId: getCours
      summary: Get all courses
      description: Get all cours with details
      responses:
        200: 
          description: List of courses
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Courses'
        400:
          description: Bad request
    post: 
      tags:
        - Courses
      operationId: createCours
      summary : Create new course
      description: Create new course
      requestBody:
        description: Cours to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCourses'
        required: true
      responses:
        200:
          description: List of courses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courses'
        400:
          description: Bad request
    put: 
      tags:
        - Courses
      operationId: createCours
      summary : Update one course
      description: Update course
      requestBody:
        description: Cours to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCourses'
        required: true
      responses:
        200:
          description: List of courses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courses'
        400:
          description: Bad request
    patch: 
      tags:
        - Courses
      operationId: createCours
      summary : Update one course
      description: Update course
      requestBody:
        description: Cours to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCourses'
        required: true
      responses:
        200:
          description: List of students
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courses'
        400:
          description: Bad request
 /student/{id}:
   get:
      tags:
        - Students
      operationId: getStudents
      summary: Get one student
      description: Get one students with details
      responses:
        200: 
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Student'
        400:
          description: Bad request
   delete: 
      tags:
        - Students
      operationId: deleteStudent
      summary : Delete student
      description: Delete student
      responses:
        200:
          description: student deleted successfuly
        400:
          description: Bad request
 /Course/{id}:
    get:
      tags:
        - Courses
      operationId: getCours
      summary: Get all courses
      description: Get all cours with details
      responses:
        200: 
          description: List of courses
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Courses'
        400:
          description: Bad request
    delete: 
      tags:
        - Courses
      operationId: deleteStudent
      summary : Delete course
      description: Delete course
      responses:
        200:
          description: course deleted successfuly
        400:
          description: Bad request
components:
  schemas:
    PhoneNumbers:
      type: array
      items:
        properties:
          country-code:
            type: string
            example: "+261"
          Numbers:
            type: string
            example: "347570893"


    CreateStudent:
      type: object
      properties:
        name:
          type: string
          example: "Rakoto"
        birth_date:
          type: string
          format: date
          example: "2022-01-01"
    Student:
      allOf:
        - $ref: '#/components/schemas/CreateStudent'
      type: object
      properties:
        id:
          type: integer
          example: 10
    CreateCourses:
      type: object
      properties:
        name:
          type: string
          example: "EL1P1"
        teacher:
          type: string
          example: "Mr Ryan"
        createdDate:
          type: string
          format: date
          example: "2022-01-01"
    Courses:
      allOf:
        - $ref: '#/components/schemas/CreateCourses'
      type: object
      properties:
        id:
          type: integer
          example: 10
        
